default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  host: localhost
  port: 5432
  pool: 5

test:
  <<: *default
  database: ong_help_test

development:
  <<: *default
  database: ong_help_dev

production:
  <<: *default
  database: ong_help_prod